name = "image-bg-remover"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# API Key is set via Cloudflare Dashboard env vars